### PR TITLE
chore: k8s-25/main branch and all corresponding wiring

### PR DESCRIPTION
**Pull request by ryparker**
## Summary

This PR adds K8s-25 to the repo. I didn't update the docs because we're moving the plus/ docs to the cdk8s-plus repo. 

Issue: 
- https://github.com/cdk8s-team/cdk8s-plus/issues/1131

Parent branch PR for moving docs/plus files from cdk8s repo to cdk8s-plus repo:

- https://github.com/cdk8s-team/cdk8s/pull/1005

## Merge order

A few of my PRs touch a lot of the same code so i've documented a merge strategy. See:

- https://github.com/cdk8s-team/cdk8s-plus/pull/1224

### CODE REVIEW

**Comment by ryparker** [comment]
Looks like i'll need to update the src/api-resource-generated.ts as well. Working on this now.

**Comment by ryparker** [comment]
Looks like we'll need to merge the v25 spec on its own first so that the CLI can import the spec and generate types in cdk8s-plus. 

Either that or we can modify the cdk8s-cli to accept a source URL override and modify cdk8s-plus's projen to accept a CLI arg that passes a custom url (e.g. `https://raw.githubusercontent.com/cdk8s-team/cdk8s/k8s-25/kubernetes-schemas/v${apiVersion}/_definitions.json`) to the cdk8s-cli. Seems like a lot of work for something we do only when kubernetes upgrades. So i'm leaning towards doing the former.

**Comment by ryparker** [comment]
All is good on the cdk8s+ release side. Now i've just got to update the CDK8s docs with the v1.25 syntax and get the CDK8s+ docs ready as well.

- [ ] cdk8s docs updated to v1.25.0 syntax
- [ ] cdk8s+ docs updated to v1.25.0 syntax

**Comment by ryparker** [comment]
Changed target branch from master to `parkerzr/move-cdk8s-plus-docs-to-cdk8s-plus-repo` so that the merge order is easier to understand.

**Review by vinayak-kukreja — APPROVED** [review]

**Pull request merged**
