### PR TITLE
chore(examples): Minor code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
### Summary of changes
- Replace variables with const
- Replace var with let or const

---

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by iliapolo** [comment]
@withshubh We cannot accept this contribution in its current form as it contains an integration with a 3rd party tool we are not familiar with nor discussed. 

I'm happy to accept the code changes themselves but notice they require an update to our integration test snapshots. 
If you'd like to suggest using `DeepSource` - please raise a separate issue where we can have a discussion on.

**Comment by withshubh** [comment]
@iliapolo Thanks for your review. :sparkling_heart: 

I have removed the `.deepsource.toml` file and created an issue for the same.

**Review by iliapolo — DISMISSED** [review]

**Comment by iliapolo** [comment]
@withshubh Im happy to merge these changes, but they actually require a re-generation of our integration tests.

**Comment by withshubh** [comment]
> @withshubh Im happy to merge these changes, but they actually require a re-generation of our integration tests.

So anything from my end?

**Comment by iliapolo** [comment]
@withshubh Yeah, you need to update the snapshots by running the integration tests in update mode locally. See https://github.com/awslabs/cdk8s/blob/master/CONTRIBUTING.md#integration-tests.

Thanks

**Comment by withshubh** [comment]
> @withshubh Yeah, you need to update the snapshots by running the integration tests in update mode locally. See [awslabs/cdk8s@`master`/CONTRIBUTING.md#integration-tests](https://github.com/awslabs/cdk8s/blob/master/CONTRIBUTING.md#integration-tests).
> 
> Thanks

Working on it.

**Review by eladb — APPROVED** [review]

**Comment by iliapolo** [comment]
@withshubh You still working on this?

**Pull request closed without merging**
