### PR TITLE
chore: migrate repo to projen

### PR DESCRIPTION
**Pull request by eladb**
Reimplement project setup using projen so we can use dependency upgrades and other goodies.

---

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by iliapolo — CHANGES_REQUESTED** [review]
Lets also add the `projenUpgradeSecret` so that we have projen upgrades?

**Comment by eladb** [comment]
> Lets also add the `projenUpgradeSecret` so that we have projen upgrades? 

@iliapolo Done

**Comment by iliapolo** [comment]
> > Lets also add the `projenUpgradeSecret` so that we have projen upgrades?
> 
> @iliapolo Done

@eladb Where is the `upgrade-projen` workflow..?

**Comment by eladb** [comment]
Working on it. I need to synthesize

**Pull request merged**
